FROM node:15 AS builder
WORKDIR /usr/src/app
COPY . .
EXPOSE 3000
CMD ["node", "index.js"]

# Image Final 
FROM node:15-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src /usr/src
EXPOSE 3000
CMD ["npm", "start"]




